// Copyright 2021 Manna Harbour
// https://github.com/manna-harbour/miryoku

#define MIRYOKU_ALPHAS_QWERTY\n#define MIRYOKU_TAP_QWERTY\n#define MIRYOKU_EXTRA_QWERTY\n#define HYPR LC(LA(LG(LSHFT)))\n#define MIRYOKU_MAPPING_LEFTPINKY_HOME &mt HYPR A\n#define MIRYOKU_MAPPING_RIGHTPINKY_HOME &mt HYPR QUOT\n#define MIRYOKU_MAPPING_LEFTINDEX_HOME &mt LGUI G\n#define MIRYOKU_MAPPING_RIGHTINDEX_HOME &mt LGUI H\n#define MIRYOKU_MAPPING_NUM_RIGHTPINKY_BOTTOM &kp NONUS_HASH
